# Generated by Django 2.1.4 on 2019-08-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Celebrity', max_length=255)),
                ('image', models.ImageField(null=True, upload_to='celebrity_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Topic', max_length=255)),
                ('image', models.ImageField(null=True, upload_to='topic_image/')),
            ],
        ),
    ]
